// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRbIGU9PLLXnII1t_tLaoRZc0b5hEmYgk',
    appId: '1:961794601892:web:3de1f9f2183e2e04010731',
    messagingSenderId: '961794601892',
    projectId: 'inventory2-e1a3f',
    authDomain: 'inventory2-e1a3f.firebaseapp.com',
    storageBucket: 'inventory2-e1a3f.appspot.com',
    measurementId: 'G-NLYCGKZDMK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-pnMYwiI_-2_DG9ZG5fMMVMGtM7irfpI',
    appId: '1:961794601892:android:48b57de3c5a66997010731',
    messagingSenderId: '961794601892',
    projectId: 'inventory2-e1a3f',
    storageBucket: 'inventory2-e1a3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1g_eCPhuidB4kPSZGTjWa3uSqmzvpkk0',
    appId: '1:961794601892:ios:4aafec1b1b002bc3010731',
    messagingSenderId: '961794601892',
    projectId: 'inventory2-e1a3f',
    storageBucket: 'inventory2-e1a3f.appspot.com',
    iosClientId: '961794601892-qq39p5262ibceee0h8tt69o2tr5bh922.apps.googleusercontent.com',
    iosBundleId: 'com.example.inventorymanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1g_eCPhuidB4kPSZGTjWa3uSqmzvpkk0',
    appId: '1:961794601892:ios:4aafec1b1b002bc3010731',
    messagingSenderId: '961794601892',
    projectId: 'inventory2-e1a3f',
    storageBucket: 'inventory2-e1a3f.appspot.com',
    iosClientId: '961794601892-qq39p5262ibceee0h8tt69o2tr5bh922.apps.googleusercontent.com',
    iosBundleId: 'com.example.inventorymanagement',
  );
}
