// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEU0DEKlSkIjkkmcYjEriB8lhMf0TVlu8',
    appId: '1:577320009049:web:0b49a67cd519c13be6e048',
    messagingSenderId: '577320009049',
    projectId: 'inventory-b84c0',
    authDomain: 'inventory-b84c0.firebaseapp.com',
    storageBucket: 'inventory-b84c0.appspot.com',
    measurementId: 'G-TDH1RNH1DP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAbL0az0DlT_LPKqMrR_Ahyz0NLgbSCQo',
    appId: '1:577320009049:android:a2646831efb74a5ae6e048',
    messagingSenderId: '577320009049',
    projectId: 'inventory-b84c0',
    storageBucket: 'inventory-b84c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_Xla_ntqUsdoBTufmAYIFwXT_-6zJ8pg',
    appId: '1:577320009049:ios:594e029b3c849a42e6e048',
    messagingSenderId: '577320009049',
    projectId: 'inventory-b84c0',
    storageBucket: 'inventory-b84c0.appspot.com',
    iosClientId: '577320009049-psu9t1pl7r2dbis4gqj445u638625a2d.apps.googleusercontent.com',
    iosBundleId: 'com.example.inventorymanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_Xla_ntqUsdoBTufmAYIFwXT_-6zJ8pg',
    appId: '1:577320009049:ios:594e029b3c849a42e6e048',
    messagingSenderId: '577320009049',
    projectId: 'inventory-b84c0',
    storageBucket: 'inventory-b84c0.appspot.com',
    iosClientId: '577320009049-psu9t1pl7r2dbis4gqj445u638625a2d.apps.googleusercontent.com',
    iosBundleId: 'com.example.inventorymanagement',
  );
}
